# nvfetcher.toml
[osquery]
#src.github = "osquery/osquery"
src.manual= "5.2.0"
fetch.url = "https://github.com/osquery/osquery/releases/download/$ver/osquery_$ver-1.linux_amd64.deb"
src.prefix = "v"

[nix-unstable-installer]
src.github = "numtide/nix-unstable-installer"
fetch.url = "https://github.com/numtide/nix-unstable-installer/releases/download/$ver/install"
src.prefix = "v"


[brim]
src.github = "brimdata/brim"
fetch.url = "https://github.com/brimdata/brim/releases/download/v$ver/Brim-$ver.deb"
src.prefix = "v"


[broker]
src.git = "https://github.com/zeek/broker"
fetch.github = "zeek/broker"
git.fetchSubmodules = true


[broker-to-json]
src.github = "grigorescu/broker-to-json"
fetch.github = "grigorescu/broker-to-json"

[vailyn]
src.github = "VainlyStrain/Vailyn"
fetch.github = "VainlyStrain/Vailyn"

[sybilhunter]
src.git = "https://github.com/NullHypothesis/sybilhunter"
fetch.github = "NullHypothesis/sybilhunter"


[eZeeKonfigurator]
src.git = "https://github.com/esnet/eZeeKonfigurator"
fetch.github = "esnet/eZeeKonfigurator"

[eZeeKonfigurator_client]
src.git = "https://github.com/esnet/eZeeKonfigurator_client"
fetch.github = "esnet/eZeeKonfigurator_client"

[elastalert2]
src.git = "https://github.com/jertel/elastalert2"
fetch.github = "jertel/elastalert2"

[choochoo]
src.git = "https://github.com/andrewcooke/choochoo"
fetch.github = "andrewcooke/choochoo"

#################
# Python fastai #
#################
[fastai]
src.git = "https://github.com/fastai/fastai"
fetch.github = "fastai/fastai"

[fastcore]
src.git = "https://github.com/fastai/fastcore"
fetch.github = "fastai/fastcore"

[fastprogress]
src.pypi = "fastprogress"
fetch.pypi = "fastprogress"


[zat]
src.git = "https://github.com/SuperCowPowers/zat"
fetch.github = "SuperCowPowers/zat"

[cliche]
src.git = "https://github.com/kootenpv/cliche"
fetch.github = "kootenpv/cliche"



#Python Packages
[btest]
src.pypi = "btest"
fetch.pypi = "btest"

[durationpy]
src.pypi = "durationpy"
fetch.pypi = "durationpy"



#Go Pkgs
[ghq]
src.git = "https://github.com/x-motemen/ghq"
fetch.github = "x-motemen/ghq"

[gst]
src.git = "https://github.com/uetchy/gst"
fetch.github = "uetchy/gst"


# [deepsea]
# src.manual= "b48e9302d079ed9f53a9123a805096a845d2c6a5"
# fetch.github = "dsnezhkov/deepsea:b48e9302d079ed9f53a9123a805096a845d2c6a5"
[go-nfsd]
src.git = "https://github.com/mit-pdos/go-nfsd"
fetch.github = "mit-pdos/go-nfsd"



[zed]
src.git = "https://github.com/brimdata/zed"
fetch.github = "brimdata/zed"

[nvdtools]
src.git = "https://github.com/facebookincubator/nvdtools"
fetch.github = "facebookincubator/nvdtools"
